### PR TITLE
Adding sendgrid email configuration

### PR DESCRIPTION
**Pull request by Williano**
I can push how i did it to this repo if you want.

### CODE REVIEW

**Comment by nitely** [comment]
The purpose of this repo is having an easy way to deploy spirit into heroku (i.e hit a button, fill some form and done). This PR defeats that purpose. If you make one that adds optional support for sendgrid in an easy to deploy way, I'll merge it. You've most of he work done here, just add the settings (make them optional), update the requirements file and test the deploy in your repo.

**Comment by Williano** [comment]
Actually I have forked and made that setting and here is the link and is working perfectly :

https://github.com/Williano/spirit-heroku

Check if it is ok.

It is working here perfectly: 

https://ghana-pyladies-forum.herokuapp.com

**Comment by nitely** [comment]
Sendgrid must be optional and take the config from the env. Something like this:

```python
# ...
EMAIL_USE_TLS = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', "")
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))

# Email credentials
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', "")
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', "")
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', "")
SERVER_EMAIL = DEFAULT_FROM_EMAIL

SENDGRID_SANDBOX_MODE_IN_DEBUG = False  # no idea what this is
SENDGRID_API_KEY = os.environ.get('SENDGRID_API_KEY', "")
if SENDGRID_API_KEY:
    EMAIL_BACKEND = "sendgrid_backend.SendgridBackend"
    # change more setting here?
```

And then add the `SENDGRID_API_KEY` entry into the [app.json](https://github.com/nitely/spirit-heroku/blob/master/app.json). After you do that, there should be a new form field for the api key thing in the deploy form. I don't have a sendgrid account to try.

**Comment by Williano** [comment]
Actually I use this Django app https://github.com/sklarsa/django-sendgrid-v5 that relies sendgrid's REST API for message delivery.

I’ve added it to the requirements.txt 

So I will modify the changes you’ve requested and let you know if it works.

**Pull request closed without merging**
